//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Ticket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinemaTicketDBEntities : DbContext
    {
        public CinemaTicketDBEntities()
            : base("name=CinemaTicketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Hall> Hall { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Seance> Seance { get; set; }
        public virtual DbSet<Ticket> Ticket { get; set; }
        public virtual DbSet<Typeplace> Typeplace { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
